### ISSUE TITLE
Bring more brand elements in

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/teamwilder#112]
## Pre-requisite

- [x] Emma make designs
- [x] e.g. put icons into the sideways teardrop of the logo?

## Acceptance criteria

- [ ] There are branded icons used throughout #47 + more?
- [ ] The correct colours are used as shown in the design #110 
- [ ] The correct typefaces are used as shown in the design #115 
- [ ] #127

**Comment by undividual** [comment]
New designs below. I still need to create all the teardrop icons as .eps files for you. 

I am also wondering if I really DO need to make these into XD files. Do let me know your thoughts on that (Katja, Alfie, Ivan or Rosie! Not @ ing you as it's the weekend, will follow up Mon)

![MVPWireframes_1Homepage](https://user-images.githubusercontent.com/90701712/232233224-4deb2242-cef6-4a80-9246-5b925ee24531.jpg)
![MVPWireframes_2Guide](https://user-images.githubusercontent.com/90701712/232233229-1fbb2315-c481-4366-943b-7bd36b0a551c.jpg)
![MVPWireframes_3Submit](https://user-images.githubusercontent.com/90701712/232233233-49f08841-ef24-473d-8ab8-80b94015ea02.jpg)
![MVPWireframes_4CaseStudy](https://user-images.githubusercontent.com/90701712/232233235-8bba78a7-25be-4c81-9cb6-7e6fa027d528.jpg)

**Comment by undividual** [comment]
EPS files for the icons here:
https://www.dropbox.com/sh/5rxaz26opzhmzco/AAD1RISCvDjEwnSwhpOeLDO3a?dl=0

**Comment by undividual** [comment]
There's also a bunch of placeholder images here if useful: https://www.dropbox.com/sh/axkiw3om9m5rsbw/AAA0tiu094id6k-jfDQYskNPa?dl=0

**Comment by katjam** [comment]
@undividual Is it easy for you to make the acceptance criteria more specific here? If not someone else can do it according to your designs, but I'll leave you assigned to give you first chance. My main worry is that as it's defined at the moment, it's openended.

**Comment by undividual** [comment]
@katjam I have had a go above!

**Comment by katjam** [comment]
Closing as everything has been converted to sub issues.
