### ISSUE TITLE
Display Privacy policy in Welsh and English

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/teamwilder#117]
## Acceptance criteria

- [x] privacy policy page has same content as https://www.wildlifetrusts.org/privacy-policy
- [x] content written in markdown and formatted similarly, but not expandable/collapsible
- [x] #120

## Implementation plan
_This plan for new issue #120 made before chatting with Katja about CMS - may need changing once #7 is complete_
- [x] Create & hook up english privacy policy
- [x] Create welsh and english folders in pages
- [x] Ensure all pages are loaded into JSON
- [x] Change routing to take language into consideration when displaying a page

**Comment by katjam** [comment]
@r-ferrier can I take you off of this?

**Comment by r-ferrier** [comment]
> @r-ferrier can I take you off of this?

absolutely! I've removed myself
