### ISSUE TITLE
[Bug]: Are cloudflare preview links broken because of something we did?

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/teamwilder#151]
## Description

The preview links in Pull Requests are broken (for Katja at least)

## Acceptance Criteria

- [ ] I can visit a cloudflare preview link
- [ ] Routing in the app works on Netlify deploy
- [ ] Routing in the app works on Cloudflare deploy

## Implementation Plan

- [ ] TBC

**Comment by katjam** [comment]
@r-ferrier if this is for netlify https://github.com/geeksforsocialchange/teamwilder/blob/23862a5bd25d723a99c01ac6d9caa04113b483f4/public/_redirects

Maybe better to put in a `netlify.toml` for that config like:

```
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
```
