### ISSUE TITLE
[Bug]: CMS tweaks

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/teamwilder#187]
## Description
Changes we need to make to CMS - arose from conversation with TW about content structure

## Acceptance Criteria
- [ ] The CMS has a ‘Summary’ field (to be used as the intro para & SEO description). Mandatory field.
- [ ] The summary field appears on guides page
- [ ] The summary field appears on guide/xx page
- [ ] The CMS for guides has a ‘photo credit’ field to add text-based content (who took the photo)
- [ ] In Guide content, the ‘related stories’ & related guides are selectable, not free text
- [ ] The Guides content type does not have a location field
- [ ] #193
- [ ] Sories have a credit and caption field for images
- [ ] Stories have a ‘postcode’ field (in addition to the where and who). Still just free text - will not be used anywhere public facing at the moment

## Implementation plan

- [ ] Make the changes listed in the CMS. 
- [ ] Create issues to add to new fields to decode / display

## Generate issues for display & decode from this list
- [ ] Display optional photo credit for guide images
- [ ] #54 - Add summary for all content types to description
- [ ] Decode & display related guides and stories
- [ ] Decode & display optional credit and caption on story images
- [ ] Decode & display who and where in stories

**Comment by katjam** [comment]
Here is what we have at the moment. In Welsh and English! Four categories/themes/subjects/whatever they are. I think they are best described as categories?

 

Grwpiau Cymunedol – Gweinyddol a Gwybodaeth / Community Groups – Admin and Information
[Mathau o Grwpiau Cymunedol (Cymru a Lloegr)](https://www.wildlifetrusts.org/sites/default/files/2022-10/TypesOfGroup_TRANS_CYM.pdf) / [Types of community group](https://www.wildlifetrusts.org/sites/default/files/2022-10/TypesOfGroup_CYM.pdf) 
[Sefydlu grŵp cymunedolsylfaenol ](https://www.wildlifetrusts.org/sites/default/files/2022-10/SettingUpACommunityGroup_TRANS_CYM.pdf)/ [Setting up a community group ](https://www.wildlifetrusts.org/sites/default/files/2022-10/SettingUpCommunityGroup_B_CYM.pdf)
[A ddylai ein grŵp ni gael cyfansoddiad?](https://www.wildlifetrusts.org/sites/default/files/2023-01/ConstitutedGroups_TRANS_CYM.pdf) / [What is a constituted group?](https://www.wildlifetrusts.org/sites/default/files/2022-11/ConstitutedGroups_CYM.pdf)
[Cyfrifon Banc ar gyfer Grwpiau](https://www.wildlifetrusts.org/sites/default/files/2022-10/BankAccountsForGroups_TRANS_CYM.pdf) / [Bank accounts for groups](https://www.wildlifetrusts.org/sites/default/files/2022-10/BankAccountsForGroups_CYM.pdf) 
[Yswiriant ar gyfer grwpiau lleol](https://www.wildlifetrusts.org/sites/default/files/2022-10/HowAreLocalGroupsInsured_TRANS_CYM.pdf) / [How are local groups insured?](https://www.wildlifetrusts.org/sites/default/files/2022-10/HowAreLocalGroupsInsured_CYM.pdf) 
[Asesiadau Risg](https://www.wildlifetrusts.org/sites/default/files/2022-10/RiskAssessments_TRANS_CYM.pdf) / [Basic risk assessments](https://www.wildlifetrusts.org/sites/default/files/2022-10/RiskAssessments_CYM.pdf)
[Dod o Hyd i Gyllid](https://www.wildlifetrusts.org/sites/default/files/2022-10/FindingFunding_TRANS_CYM.pdf) / [Finding funding](https://www.wildlifetrusts.org/sites/default/files/2022-10/FindingFunding_CYM.pdf) 
[Sut i Wneud Cais am Gyllid](https://www.wildlifetrusts.org/sites/default/files/2022-10/HowToApplyForFunding_TRANS_CYM.pdf) / [How to apply for funding](https://www.wildlifetrusts.org/sites/default/files/2022-10/HowToApplyForFunding_CYM.pdf) 
[How to recruit a Community Organiser ](https://www.wildlifetrusts.org/sites/default/files/2023-02/Guide-to-Recruiting-a-Community-Organisers_FV.pdf)- detailed information from NACO (English only at this stage)
Cyfryngau, Cyhoeddusrwydd a Digwyddiadau / Media, Publicity and Events
[Sut i Gynnal Digwyddiad Codi Arian](https://www.wildlifetrusts.org/sites/default/files/2022-10/HowToRunAFundraisingEvent_TRANS_CYM.pdf) / [How to run a fundraising event ](https://www.wildlifetrusts.org/sites/default/files/2022-10/HowToRunAFundraisingEvent_CYM.pdf)
[Datganiadau i'r Wasg – cyfarwyddyd](https://www.wildlifetrusts.org/sites/default/files/2023-01/PUBLICPressReleaseGuidance_TRANS_CYM.pdf) / [How to write a press release](https://www.wildlifetrusts.org/sites/default/files/2022-10/PUBLICPressReleaseGuidance_CYM.pdf)
Gweithio gyda Phobl / Working with People
[Ymgysylltu cymunedol amlieithog](https://www.wildlifetrusts.org/sites/default/files/2022-10/MultilingualCommunityEngagement_TRANS_CYM.pdf) / [Working with many languages](https://www.wildlifetrusts.org/sites/default/files/2022-10/MultilingualCommunityEngagement_CYM.pdf)
[Cynghorion Ymarferol ar gyfer Cyfathrebu Traws-ddiwylliannol ](https://www.wildlifetrusts.org/sites/default/files/2023-01/PracticalTipsCrossCulturalCommunication_TRANS_CYM.pdf)/ [Cross-cultural communication](https://www.wildlifetrusts.org/sites/default/files/2022-11/PracticalTipsCrossCulturalCommunication_CYM_rev2.pdf)
[Sicrhau bod pawb yn gallu cael mynediad at eich grŵp neu brosiect](https://www.wildlifetrusts.org/sites/default/files/2023-01/EnsuringAccessibility_TRANS_CYM.pdf) / [Making sure everything is accessible](https://www.wildlifetrusts.org/sites/default/files/2022-11/EnsuringAccessibility_CYM.pdf)
[Rheoli gwrthdaro mewn grŵp](https://www.wildlifetrusts.org/sites/default/files/2023-01/ManagingConflict_TRANS_CYM.pdf) / [Managing conflict in a group](https://www.wildlifetrusts.org/sites/default/files/2023-01/ManagingConflict_CYM.pdf)
Gweithio gyda'r Awdurdodau / Working with the Authorities
[Rheoli gofod gwyrdd yn eich ardal ](https://www.wildlifetrusts.org/sites/default/files/2023-01/TakingOverGreenSpace_TRANS_CYM.pdf)/ [Taking over green space](https://www.wildlifetrusts.org/sites/default/files/2022-10/TakingOverGreenSpace_CYM.pdf)
[Sut i gysylltu â'ch AS](https://www.wildlifetrusts.org/sites/default/files/2022-10/ContactYourMP_TRANS_CYM.pdf) / [How to contact your MP](https://www.wildlifetrusts.org/sites/default/files/2022-10/ContactYourMP_CYM.pdf)
[Beth mae cynghorau ac awdurdodau lleol yn ei wneud?](https://www.wildlifetrusts.org/sites/default/files/2023-01/AboutCouncilsAndLAs_TRANS_CYM.pdf) / [All about councils and local authorities](https://www.wildlifetrusts.org/sites/default/files/2022-10/AboutCouncilsAndLAs_CYM.pdf) 
[Siarad â Chynghorau, Cynghorwyr a Phobl mewn Awdurdod](https://www.wildlifetrusts.org/sites/default/files/2023-01/SpeakingToCouncils_TRANS_CYM.pdf) / [Speaking to councils with confidence - practical tips](https://www.wildlifetrusts.org/sites/default/files/2022-11/SpeakingToCouncils_CYM.pdf)

**Comment by katjam** [comment]
Verified:
![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/065c3fc5-2260-48b0-9706-821496e44ecf)
![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/fa1bc1ed-7af6-4b52-8391-2c64ecb557a1)
![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/15cba5da-f251-4e8f-b28b-429b9e77782d)
![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/35c8f2bc-bc2d-47b9-924c-778aee4e5ad6)
![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/d656e2be-0410-490d-93e7-0bef0d5fba55)
![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/93c236b7-eb5e-462d-a620-12e58c0f4267)
![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/0c83809e-46ea-4b25-a90c-d9b9ea123c48)
