### ISSUE TITLE
Display optional photo credit for guide images

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/teamwilder#199]
## Acceptance Criteria

- [ ] If a guide image has a credit, it is displayed on the guide page
- [ ] If a guide image has a credit it is NOT displayed on the teaser
- [ ] If a guide has an image, it is displayed at the top of the guide page (see screenshot)

**NOTE:** Display of summary & other layout changes will be incorporated in #217 

## Implementation plan

- [ ] Change guide image type
- [ ] Refactor Guide teaser data to live in guide
- [ ] Alter guide view to include image in headers (with placeholder for summary & optional credit)

**Comment by undividual** [comment]
Image has now been added to design of guide pages. Required quite a bit of a rethink layout wise. Wireframe below. Each guide now has a header section which contains guide title, image, image credit and backlink. Very open to design input on this. @katjam do you think this needs to be a new ticket as the scope of this has expanded beyond just adding image credits? 
![MVPWireframes_2](https://user-images.githubusercontent.com/90701712/236448729-d0f35676-cf09-4cf0-9ab7-ea8d617c54b4.jpg)

**Comment by katjam** [comment]
Yes, @undividual I guess I'll adapt this issue to suit, because currently we don't display the image on a guide page at all.

**Comment by undividual** [comment]
I made this a new issue #217 just fyi @katjam

**Comment by katjam** [comment]
Perfect! I'll link that in the NOTE above.

**Comment by katjam** [comment]
verified and noted in Public Features:

![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/abb4aa63-6638-4e47-a627-eb635df84ff7)
![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/4be9b92f-af9c-4cd7-a79a-491ee09ff71c)

**Comment by katjam** [comment]
Note have mentioned design concerns in:
https://github.com/geeksforsocialchange/teamwilder/issues/217
