### ISSUE TITLE
Decode & display related guides and stories

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/teamwilder#200]
## Acceptance Criteria

- [ ] If a guide has related guides, teasers for them are displayed on the guide
- [ ] If a guide has related stories, teasers for them are displayed on the guide
- [ ] Guide teasers are a list of titles linked to the guide
- [ ] Story teasers are a grid of image with title underneath linking to the story (note the title has changed from the one in the design) - still TBC

![image](https://user-images.githubusercontent.com/861172/235310244-21d407c3-9720-417b-85ec-0683d2edbf9a.png)
![image](https://user-images.githubusercontent.com/861172/235310303-a6487b36-c6dd-40a7-92ca-8528aa5ad16a.png)

## Implementation plan

- [ ] Alter the decode to get title of related rather than the data
- [ ] Look-up the content from title
- [ ] Display as per designs

**Comment by katjam** [comment]
Verified and added to Public Feature wiki

![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/fabac0d0-806a-4cbd-b303-89205513f9dd)

![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/30de485f-aed4-45a9-9710-97571e666898)
