### ISSUE TITLE
Stories can be Welsh

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/teamwilder#205]
## Acceptance criteria

- [ ] If there is a Welsh version of a story I can view it

## Implementation plan
- [ ] Add `en` and `cy` dir to flags
- [ ] Decode into language keyed Dicts
- [ ] Change View to lookup from language

**Comment by katjam** [comment]
Verified and added to CMS & Public Feature wiki

![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/b78accf1-d5ec-47f9-9569-7eab3255ea07)
![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/8ead10ea-5f9d-460f-8b9a-cfc246c4ffda)
