### ISSUE TITLE
Footer broken and missing link to about page as discussed

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/teamwilder#209]
## Acceptance Criteria

- [ ] Footer links are in lists - not inline as image
- [ ] There is a link in the footer to the about page (Find out more about this project)

## Implementation plan

- [ ] Use lists for footer links
- [ ] Add about page link

**Comment by katjam** [comment]
![image](https://user-images.githubusercontent.com/861172/235358951-59a775e6-fa6d-49a2-b98c-ccea6fb0a3b9.png)

**Comment by katjam** [comment]
Verified and noted in Public Feature wiki:
![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/c0116b4c-efab-4967-bff6-8eb47242fced)
