### ISSUE TITLE
Add some navigation to the footer

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/teamwilder#28]
## User story
As a person using the site I need an obvious way to navigate around the site, so that I can easily find what I am looking for.

## Acceptance criteria
- [ ] I can see a list of links in the footer with appropriate headings (list TBC below)
- [ ] (TBC) I can tell which link I am currently on (@undividual do we want some "active state" for the footer menu links?)

## Implementation notes & questions
Probably worth adding the responsive layout for footer "columns" with this if that hasn't been done in #26

## List of links
Find out more
- [x] [Visit The Wildlife Trusts main website](https://www.wildlifetrusts.org)

Explore the library
- [x] Find a guide (links to the search page - defaults to alphabetical list)

Get involved
- [x] [Find your local trust](https://www.wildlifetrusts.org/wildlife-trusts)

## Add these when the pages are ready. #51 
 - [ ] Find out more about this project 
 - [ ] How to use this website
 - [ ] Full sitemap
 - [ ] Submit your own Case study

## Implementation plan
- [x] Create a styled container component with some flex to display columns appropriately across different screen sizes
- [x] Add list of links, urls and titles to keys
- [x] Create styled column component & implement

**Comment by katjam** [comment]
![image](https://user-images.githubusercontent.com/861172/223701018-e3d8e1fe-5555-4cd2-94f0-a7477b370c70.png)

**Comment by katjam** [comment]
@r-ferrier removed you to avoid confusion as I work on this over the weekend. Please forgive me :pray:

**Comment by r-ferrier** [comment]
Verified: Links exist in footer
