### ISSUE TITLE
Set up analytics

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/teamwilder#32]
## Description
The Wildlife Trusts have  Google Analytics 4 and Hotjar analytics available.

When we are ready the set this up 
## Acceptance Criteria
- [ ] #94
- [ ] #93
- [ ] #33

NOTE: For Alpha we can use internal GFSC accounts to test integration. When we are ready to wire up to Trust accounts, ask @katjam for appropriate contact to support this.

## Plan
- [ ] Add tracking snippet for GA #94 along with cookie banner
- [ ] Add privacy policy #33 link to footer
- [ ] Add tracking snippet for Hotjar #93

**Comment by katjam** [comment]
Closing as has been split into issues

**Comment by r-ferrier** [comment]
verifying in separate issues
