### ISSUE TITLE
Css changes

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/teamwilder#439]
All of the following link to their block in the  notion doc which contains more detail & screenshots where relevant

### General/home

- [x] [Space between each para of copy is too wide](https://www.notion.so/gfsc/TeamWilder-design-sweep-f88a5f22479c43fb958751b576d0eda8?pvs=4#dc39cef97e284f35a55adbfe939432b6)
- [x] [Remove the arrows throughout — no need for them](https://www.notion.so/gfsc/TeamWilder-design-sweep-f88a5f22479c43fb958751b576d0eda8?pvs=4#93260384d24c4355a4e6ea49ef80440e)
- [x] [Make sure there’s a decent space after share your story before footer line (currently this is very tight)](https://www.notion.so/gfsc/TeamWilder-design-sweep-f88a5f22479c43fb958751b576d0eda8?pvs=4#434a7c709ff14d3c9bd4e0e2b0c02fe8)
- [x] [First section of footer, headings are not aligned (Explore is correct, Find out and Get involved sit too far right)](https://www.notion.so/gfsc/TeamWilder-design-sweep-f88a5f22479c43fb958751b576d0eda8?pvs=4#abda631a74f74391bfcce5bb9d69018b)
- [x] [Make the text width of the paragraph on the left at the bottom of the page wider, so that it’s only 4 lines long not 5. (so it’s same height as logos)](https://www.notion.so/gfsc/TeamWilder-design-sweep-f88a5f22479c43fb958751b576d0eda8?pvs=4#9463584978564b2e8d22911b2c694f0a)
- [x]  Standard hyperlinks are purple and underlined
- [x] [With short page content (e.g. how to use this site), footer does not cling to bottom, it should do (note white section in below screenshot)](https://www.notion.so/gfsc/TeamWilder-design-sweep-f88a5f22479c43fb958751b576d0eda8?pvs=4#1102728844214340bf9661b41f0e0a9e)

### Guides index page

- [x] [Needs a bigger space after related stories before share your story](https://www.notion.so/gfsc/TeamWilder-design-sweep-f88a5f22479c43fb958751b576d0eda8?pvs=4#a3d2e4585121419797d89ba2ab437d21)
- [x] [Main title of guides page should align with text and all the other images (i.e. here ‘How to run a fundraising event’ and its subtitle should move to the right to align with the nextdoor nature hub and the image and text guide below)](https://www.notion.so/gfsc/TeamWilder-design-sweep-f88a5f22479c43fb958751b576d0eda8?pvs=4#afc5fb6bf33b44458febe28ecc6f93a5)

### Ancillary pages

- [x] [privacy policy - know I haven’t wireframed this but can we make this column width narrower? Either run it down the centre of the page (easiest for now) or make it run down the left half of the page and add images down the right on desktop view for decoration like on the form submission page?](https://www.notion.so/gfsc/TeamWilder-design-sweep-f88a5f22479c43fb958751b576d0eda8?pvs=4#06af00ac714a48dda6315fc9dabe023d)

**Comment by r-ferrier** [comment]
@undividual which arrows are going and which are staying? Some conflicting requests here to remove them throughout and to ensure they remain on the same line as a link

**Comment by undividual** [comment]
Apols — the outcome from the last meeting was 'just remove them all' which negates the issue of making sure they're on the same line!

**Comment by katjam** [comment]
Verified:
![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/9c11c922-e270-47d7-99b7-bf4d24596a25)
![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/0b7e5b2b-3f96-4617-90cf-b53121f3c572)

**Comment by katjam** [comment]
verified:
![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/fcbc8057-04a0-4bc3-a2bd-112497abc973)

![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/8d426c6c-122a-4208-854e-969dde5b8445)

**Comment by katjam** [comment]
Narrow column:
![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/767ae62e-6fde-483b-b9f0-2f73d9d6b677)
