### ISSUE TITLE
I can add and edit the nextdoor nature resource in markdown

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/teamwilder#48]
## Acceptance Criteria
- [ ] I can add nextdoor nature content in markdown
- [ ]  When I add a new nextdoor nature guide in markdown, the site includes it 
- [ ] #62
- [ ]  #81 
- [ ] The readme makes it clear how content is generated

## Implementation Plan

- [x] Generate a couple markdown files with fields as per Resource + unique slug (may not enforce uniqueness before CMS integration)
- [x] add a minimal guide
- [x] convert md files to json on build (& dev?)
- [x] decode generated Json
- [x] lookup from slug / Populate Resource page view from template
- [x] update readme
- [x] remove dummy guide content
- [x] add a full guide
- [x] #85
- [x] #86
- [x] key guides by slug

**Comment by katjam** [comment]
@ivan-kocienski-gfsc I guess it wasn't obvious from the #62 ticket that that it was a follow-on from this as one of the AC. Sorry. I thought it would come out at the bottom of the milestone when I converted it. I'm double checking the order of the rest now.

**Comment by ivan-kocienski-gfsc** [comment]
@katjam no not really, i think i wrote the description for #62. I thought it was a "if we had multiple languages how would we switch between them?" situation.

I would have thought getting CMS integration would be prerequisite for this. I am interested to see how elm can save state on the server.

**Comment by katjam** [comment]
The server in our case is the browser and the CMS storage is markdown files. The CMS GUI will be an editor for those markdown files. #62 is a follow on from this because we needed the markdown files to be wired in before stubbing out the translation fields in them. Emma and I thought something like:

title:
  en: "My english title"
  cy: "My Welsh title"

I'll add details to #62.

Elm state is only held until "refresh" unless you implement session or local storage which is most likely out of scope for this project. We will init the site in English and the user can then select Welsh using the toggle you made.

**Comment by r-ferrier** [comment]
verified: guides added with the CMS are appearing in our codebase and being imported by the site

<img width="509" alt="Screenshot 2023-05-29 at 16 35 49" src="https://github.com/geeksforsocialchange/teamwilder/assets/46496391/7264a85a-4a1c-4d18-8d82-87716210241c">
![Screenshot 2023-05-29 at 16 34 38](https://github.com/geeksforsocialchange/teamwilder/assets/46496391/775cef89-0ac9-4603-be6f-49c14c42b194)
![Screenshot 2023-05-29 at 16 34 31](https://github.com/geeksforsocialchange/teamwilder/assets/46496391/28687de5-ffed-45f5-aa43-b45a362fb085)
