### ISSUE TITLE
Set up SEO meta in head

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/teamwilder#54]
## Acceptance criteria

- [ ] Each page has a (probably unique) meta title
- [ ] Each page has a suitable meta description
- [ ] Each page has og image tags (with default or suitable image)
- [ ] Each page has twitter card spec meta
- [ ] robots no-follow added to dev & alpha sites
- [ ] There is a go-live step to undo the no-follow robots & set up `VITE_BASE_URL` environment variable

## Implementation plan

- [x] Add robots no follow & an issue to undo that for production in next release
- [x] Add port & meta update hooks
- [x] Construct meta title from page title | siteTitle
- [x] Add description field to markdown templates for pages (or use summary if exists)
- [x] content lookup from language
- [x] Wire in default image and issue to update with approved (added to #324)
- [x] Use image in content as og image (if there is one - otherwise default)
- [x] Add twitter spec meta from best guess at various content fields
- [x]  slugs are being used instead of looked up values from the content guide (DONE), story
- [x] add url base from env in front of image
