### ISSUE TITLE
Review accessibility and markup for video component

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/teamwilder#56]
We stubbed this into the Alpha release because there is evidence that people want video content & TW have video content ready, but before the public release, we need to consider the accessibility of the component.

## Accessibility items and their provisions

Items provided by Youtube by default
- Visible controls
- Keyboard navigation
- "Watch on Youtube" button that will take them to the Youtube video page

Items that need to be provided by the client on any video they wish to embed:
- Captions (these can be auto-generated but will be better hand-written)
- Transcript (these can be auto-generated but will be better hand-written)
- Different audio tracks (?) (different languages, more descriptive language)

Items specific to the Nextdoor Nature platform
- Video summary #388 
- Audio alternate content (backlog or never)

## Notes

[This video](https://www.youtube.com/watch?v=Hgw9oXeWJFQ) is a sample video from client

Which can be seen in situ [here](http://localhost:5173/guides/test-guide-with-all-content).

## Acceptance Criteria

Embedded videos:
- [ ] are keyboard navigable
- [ ] have transcripts (only appears on youtube site (through link) can be auto-generated)
- [ ] have visible captions
- [ ] obey the rest of the sites layout rules
- [ ] provide on screen controls

## TODO

- [ ] Test with screen reader

**Comment by katjam** [comment]
According to Autumn the video content is vital to this campaign, so I suggest we prioritise this & make sure the accessibility stuff is embedded / used in YouTube where possible + have some transcripts available on this side.

**Comment by ivan-kocienski-gfsc** [comment]
This seems like interesting reading https://www.boia.org/blog/are-embedded-youtube-videos-bad-for-accessibility

**Comment by katjam** [comment]
@ivan-kocienski-gfsc In your research, didn't you split the AC into things we control from this site and things Autumn needs to do on YouTube?

We need that info here, so we know who needs to do what.

**Comment by katjam** [comment]
Thanks @ivan-kocienski-gfsc I'm closing this as done now since the only outstanding code task has been added elsewhere & we will QA on release & Autumn is doing transcripts / subtitles already.

**Comment by katjam** [comment]
![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/4b46f0d6-7060-4d4d-b60b-5c1d426e6ca0)

**Comment by katjam** [comment]
![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/a63bac55-9310-4375-b619-7bc861056101)
