### ISSUE TITLE
I can see usage data in Google Analytics

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/teamwilder#94]
## Acceptance Criteria

- [ ] I can opt out of analytics
- [ ] If I am opted in to analytics, tracking info is sent to google
- [ ] If I am opted out of analytics, tracking info is not sent to google

## Implementaiton notes

- Alpha version will be wired up to test accounts.
- Privacy policy being added in #33 

## Implementation Plan

- [ ] Add GA tracking snippet
- [ ] Add cookie banner with opt out option as per the Trusts main site
